"""
Ghostpanel — FROZEN SHARED CONTRACTS.

⚠️  DO NOT EDIT THIS FILE.  ⚠️
This module is the single source of truth that every agent/module imports and
NONE may modify. It is committed in the skeleton before any agent starts so that
five parallel branches never touch the same file. If you believe a contract is
wrong or missing, STOP and raise it with the orchestrator (Agent 3) — a contract
change must be made once, here, and propagated, never forked per-branch.

Contents:
  * Enums                — PerturbationKind, ActionType, PersonaOutcome, EventType
  * Data models          — PersonaConfig, Observation, Action, StepRecord,
                           PersonaResult, HeatPoint, SurvivalPoint, RunReport
  * Event wire models    — RunEvent tagged union (the exact JSON the frontend renders)
  * Protocols (interfaces)— HoloClient, PersonaAgent, SessionRunner, EventSink,
                           VoiceEngine, ReportBuilder

Everything is Pydantic v2 and JSON-serializable (bytes are never put on the wire;
screenshots travel as base64 strings in StepRecord.thumbnail_b64 / RunEvent).
"""

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal, Optional, Protocol, Union, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field

# Contract version. Bump ONLY via the orchestrator when the spine legitimately
# changes; every module can assert against this to detect a stale checkout.
CONTRACT_VERSION = "1.0.0"


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------
class PerturbationKind(str, Enum):
    """Perception/actuation degradations a persona applies. Agent 1 implements each."""

    BLUR = "blur"                     # gaussian blur of the screenshot (low visual acuity)
    DOWNSCALE = "downscale"           # resize-down-then-up IN PLACE (keeps dims; low acuity)
    CVD = "cvd"                       # color-vision-deficiency filter (DaltonLens)
    TREMOR = "tremor"                 # gaussian noise added to click coordinates (motor)
    SMALL_VIEWPORT = "small_viewport" # tiny viewport / fat-finger (mobile / cracked screen)
    IMPATIENCE = "impatience"         # tight step/time budget (abandons fast)
    LOW_LITERACY = "low_literacy"     # literal reading, no inferred UI conventions (prompt mod)


class CVDType(str, Enum):
    """Color-vision-deficiency variants (map to DaltonLens Deficiency)."""

    PROTAN = "protan"
    DEUTAN = "deutan"
    TRITAN = "tritan"


class ActionType(str, Enum):
    """Holo navigation action space (mirrors hai-cookbook utils/navigation.py)."""

    CLICK = "click"       # ClickElementAction  -> page.mouse.click(x, y)
    WRITE = "write"       # WriteElementAction   -> type `text` (then Enter)
    SCROLL = "scroll"     # ScrollAction         -> direction up/down/left/right
    GO_BACK = "go_back"   # GoBackAction
    REFRESH = "refresh"   # RefreshAction
    WAIT = "wait"         # WaitAction           -> seconds (0-10)
    GOTO = "goto"         # GotoAction           -> url
    RESTART = "restart"   # RestartAction
    ANSWER = "answer"     # AnswerAction         -> final answer / task complete


class ScrollDirection(str, Enum):
    UP = "up"
    DOWN = "down"
    LEFT = "left"
    RIGHT = "right"


class PersonaOutcome(str, Enum):
    """How a persona's session ended."""

    SUCCESS = "success"              # goal achieved (AnswerAction / success predicate)
    STEP_BUDGET = "step_budget"      # ran out of steps before finishing
    TIME_BUDGET = "time_budget"      # ran out of wall-clock time
    STUCK = "stuck"                  # loop/no-progress detector tripped (gave up)
    ERROR = "error"                  # crash / infra failure (not a real "abandon")


# ---------------------------------------------------------------------------
# Persona configuration (Agent 1 authors JSON files under personas/)
# ---------------------------------------------------------------------------
class Viewport(BaseModel):
    model_config = ConfigDict(extra="forbid")
    width: int = 1280
    height: int = 800


class PersonaConfig(BaseModel):
    """A synthetic user. Persona physics are MECHANICAL, not roleplayed.

    Persona JSON files live in personas/*.json and validate against this model.
    `blur_sigma`, `downscale_factor`, `cvd_*`, `tremor_sigma_px` degrade the
    perception/actuation channels; `max_steps`/`deadline_s` model impatience;
    `literacy_note` is appended to the Holo navigation prompt.
    """

    model_config = ConfigDict(extra="forbid")

    id: str                                   # stable slug, e.g. "grandma-70"
    name: str                                 # display name, e.g. "Margaret, 72"
    blurb: str = ""                           # one line shown in the UI
    voice_id: Optional[str] = None            # Gradium voice_id for this persona (Agent 5)

    viewport: Viewport = Field(default_factory=Viewport)
    language: str = "en"                      # answer language for exit interview / prompts

    # --- perception perturbations (applied to the screenshot BEFORE Holo sees it) ---
    blur_sigma: float = 0.0                   # 0 = off; gaussian blur radius in px
    downscale_factor: float = 1.0            # 1.0 = off; e.g. 0.5 halves then restores dims
    cvd_type: Optional[CVDType] = None
    cvd_severity: float = 0.0                 # 0..1

    # --- actuation perturbation (applied to click coords AFTER Holo decides) ---
    tremor_sigma_px: float = 0.0              # 0 = off; gaussian noise sigma on (x,y)

    # --- patience / cognition ---
    max_steps: int = 30
    deadline_s: float = 120.0
    literacy_note: str = ""                   # extra instruction appended to nav prompt

    # free-form list for the UI / analytics (which channels are degraded)
    active_perturbations: list[PerturbationKind] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Observation + Action (the engine's I/O)
# ---------------------------------------------------------------------------
class Observation(BaseModel):
    """A single frame handed to a PersonaAgent. `raw_png` is the UN-perturbed
    screenshot bytes captured by the runner; the engine perturbs a copy."""

    model_config = ConfigDict(arbitrary_types_allowed=True, extra="forbid")

    raw_png: bytes                            # PNG bytes straight from Playwright
    viewport: Viewport
    step_index: int
    url: str = ""


class Action(BaseModel):
    """A decoded Holo action, already de-perturbed into TRUE viewport pixels
    (engine has applied tremor jitter and any smart_resize remap). The runner
    executes this verbatim; it never re-scales coordinates."""

    model_config = ConfigDict(extra="forbid")

    type: ActionType
    x: Optional[int] = None                   # click/write target (viewport px)
    y: Optional[int] = None
    text: Optional[str] = None                # WRITE content / ANSWER content
    direction: Optional[ScrollDirection] = None
    url: Optional[str] = None                 # GOTO
    seconds: Optional[float] = None           # WAIT
    caption: str = ""                         # human-readable, shown on the UI tile
    raw: str = ""                             # verbatim model output (for debugging)


# ---------------------------------------------------------------------------
# Per-step + per-persona records
# ---------------------------------------------------------------------------
class StepRecord(BaseModel):
    model_config = ConfigDict(extra="forbid")

    persona_id: str
    step: int
    action: Action
    thumbnail_b64: str = ""                   # small JPEG/PNG data URI of the frame (for the grid)
    latency_ms: int = 0                       # Holo round-trip
    note: str = ""


class PersonaResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    persona_id: str
    outcome: PersonaOutcome
    steps: list[StepRecord] = Field(default_factory=list)
    failure_coords: Optional[tuple[int, int]] = None   # where it died (viewport px)
    failure_step: Optional[int] = None
    failure_reason: str = ""                            # short human string
    duration_s: float = 0.0
    video_path: Optional[str] = None                    # .webm receipt
    transcript: str = ""                                # exit-interview text (Agent 5 fills)
    audio_path: Optional[str] = None                    # exit-interview .wav (Agent 5 fills)


# ---------------------------------------------------------------------------
# Report artifacts (Agent 5 builds)
# ---------------------------------------------------------------------------
class HeatPoint(BaseModel):
    model_config = ConfigDict(extra="forbid")
    x: int
    y: int
    weight: float = 1.0
    persona_id: str = ""


class SurvivalPoint(BaseModel):
    """One persona's survival summary for the survival-curve chart."""

    model_config = ConfigDict(extra="forbid")
    persona_id: str
    persona_name: str = ""
    outcome: PersonaOutcome
    steps_survived: int
    completed: bool


class RunReport(BaseModel):
    model_config = ConfigDict(extra="forbid")

    run_id: str
    target_url: str
    task: str
    contract_version: str = CONTRACT_VERSION
    results: list[PersonaResult] = Field(default_factory=list)
    survival: list[SurvivalPoint] = Field(default_factory=list)
    heatmap_points: list[HeatPoint] = Field(default_factory=list)
    completion_rate: float = 0.0              # fraction of personas that succeeded
    generated_at: str = ""                    # ISO8601, stamped by caller


# ---------------------------------------------------------------------------
# Event wire models — the exact JSON pushed over the WebSocket to the frontend.
# Discriminated union on `event`. Agent 4 renders these; Agent 3 emits them.
# ---------------------------------------------------------------------------
class EventType(str, Enum):
    RUN_STARTED = "run_started"
    PERSONA_STARTED = "persona_started"
    STEP = "step"
    PERSONA_FINISHED = "persona_finished"
    RUN_FINISHED = "run_finished"


class RunStarted(BaseModel):
    model_config = ConfigDict(extra="forbid")
    event: Literal[EventType.RUN_STARTED] = EventType.RUN_STARTED
    run_id: str
    target_url: str
    task: str
    personas: list[PersonaConfig]


class PersonaStarted(BaseModel):
    model_config = ConfigDict(extra="forbid")
    event: Literal[EventType.PERSONA_STARTED] = EventType.PERSONA_STARTED
    run_id: str
    persona_id: str


class StepEvent(BaseModel):
    model_config = ConfigDict(extra="forbid")
    event: Literal[EventType.STEP] = EventType.STEP
    run_id: str
    persona_id: str
    step: int
    caption: str                              # "clicking Sign up", "scrolling down"…
    thumbnail_b64: str = ""                   # data URI of current frame for the tile
    x: Optional[int] = None
    y: Optional[int] = None


class PersonaFinished(BaseModel):
    model_config = ConfigDict(extra="forbid")
    event: Literal[EventType.PERSONA_FINISHED] = EventType.PERSONA_FINISHED
    run_id: str
    persona_id: str
    outcome: PersonaOutcome
    failure_coords: Optional[tuple[int, int]] = None
    failure_reason: str = ""
    steps_survived: int = 0


class RunFinished(BaseModel):
    model_config = ConfigDict(extra="forbid")
    event: Literal[EventType.RUN_FINISHED] = EventType.RUN_FINISHED
    run_id: str
    report_url: str
    completion_rate: float = 0.0


RunEvent = Annotated[
    Union[RunStarted, PersonaStarted, StepEvent, PersonaFinished, RunFinished],
    Field(discriminator="event"),
]


# ---------------------------------------------------------------------------
# Protocols (interfaces). Concrete implementations live in the module owned by
# the agent named in each docstring. Concrete class names/paths are fixed in
# CLAUDE.md so the composition root (Agent 3) can import and wire them.
# ---------------------------------------------------------------------------
@runtime_checkable
class HoloClient(Protocol):
    """Wraps the Holo Models API (OpenAI-compatible). Owned by Agent 1.
    Concrete: engine.holo_client.LiveHoloClient (+ FakeHoloClient for tests)."""

    async def localize(self, image_png: bytes, instruction: str) -> tuple[int, int]:
        """Return (x, y) in the pixel space of the *image passed in*."""
        ...

    async def navigate(
        self, image_png: bytes, task: str, history: list[str]
    ) -> Action:
        """Return the next Action given a screenshot, the task, and past-action captions."""
        ...


@runtime_checkable
class PersonaAgent(Protocol):
    """Decides the next Action for one persona: perturb(image) -> Holo -> jitter.
    Owned by Agent 1. Concrete: engine.persona_agent.HoloPersonaAgent."""

    persona: PersonaConfig

    async def decide(self, obs: Observation, history: list[str]) -> Action:
        ...


@runtime_checkable
class EventSink(Protocol):
    """Where a runner pushes live events. Implemented by Agent 3 (server) and a
    no-op/collector used in tests. Must be safe to call from many tasks."""

    async def emit(self, event: BaseModel) -> None:  # event is a RunEvent member
        ...


@runtime_checkable
class SessionRunner(Protocol):
    """Drives ONE persona's browser session end to end. Owned by Agent 2.
    Concrete: runner.session.PlaywrightSessionRunner."""

    async def run(
        self,
        persona: PersonaConfig,
        agent: PersonaAgent,
        target_url: str,
        task: str,
        sink: EventSink,
        run_id: str,
    ) -> PersonaResult:
        ...


@runtime_checkable
class VoiceEngine(Protocol):
    """Gradium wrapper. Owned by Agent 5. Concrete: voice.gradium_voice.GradiumVoiceEngine."""

    async def exit_interview(self, result: PersonaResult, persona: PersonaConfig) -> str:
        """Generate + synthesize the persona's exit interview; return the .wav path.
        Also sets result.transcript / result.audio_path as a side effect is allowed."""
        ...

    async def mutter(self, text: str, voice_id: Optional[str]) -> str:
        """Synthesize a short in-run line; return the audio path."""
        ...


@runtime_checkable
class ReportBuilder(Protocol):
    """Aggregates PersonaResults into a RunReport + artifacts. Owned by Agent 5.
    Concrete: report.builder.SurvivalReportBuilder."""

    def build(
        self,
        run_id: str,
        target_url: str,
        task: str,
        results: list[PersonaResult],
        personas: list[PersonaConfig],
    ) -> RunReport:
        ...
