// Flows — a client-side sim.yml authoring helper. There is NO backend
// persistence endpoint for flows yet: this page GENERATES the YAML you commit to
// your repo, where the `simulationlabs/gate` GitHub Action reads it in CI. The
// generated field names mirror ghostpanel.cli.config (flows[].{name,url,task,
// fail_under}, icp.personas, swarm.{rpm,max_personas}, output.dir) EXACTLY.

import { useMemo, useState } from "react";
import { FlowEditor, newFlow } from "../components/FlowEditor";
import type { FlowDraft } from "../components/FlowEditor";
import { IcpPicker } from "../components/IcpPicker";
import { PERSONA_CATALOG } from "../../personaCatalog";

type IcpValue = string[] | "auto";

const ALL_IDS = PERSONA_CATALOG.map((p) => p.id);

// Escape an arbitrary string into a YAML double-quoted scalar. Double-quoted
// scalars accept backslash escapes, so this is safe for any task text.
function yamlStr(s: string): string {
  const escaped = s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t")
    .replace(/\r/g, "");
  return `"${escaped}"`;
}

function buildYaml(
  flows: FlowDraft[],
  icp: IcpValue,
  rpm: number,
  maxPersonas: number,
  outputDir: string
): string {
  const lines: string[] = [];
  lines.push(
    "# sim.yml — generated by the Simulation Labs dashboard.",
    "# Commit this to your repo root; the simulationlabs/gate Action reads it in CI.",
    "# Docs: docs/ci.md",
    "version: 1",
    ""
  );

  // flows
  lines.push("flows:");
  if (flows.length === 0) {
    lines.push("  [] # add at least one flow");
  } else {
    for (const f of flows) {
      lines.push(`  - name: ${yamlStr(f.name)}`);
      lines.push(`    url: ${yamlStr(f.url)}`);
      lines.push(`    task: ${yamlStr(f.task)}`);
      const failUnder =
        f.fail_under === "last-passing" ? "last-passing" : String(f.fail_under);
      lines.push(`    fail_under: ${failUnder}`);
    }
  }
  lines.push("");

  // icp
  lines.push("icp:");
  if (icp === "auto") {
    lines.push("  personas: auto");
  } else if (icp.length === 0) {
    lines.push("  personas: auto # (no personas selected — falls back to roster)");
  } else {
    lines.push("  personas:");
    for (const id of icp) lines.push(`    - ${id}`);
  }
  lines.push("");

  // swarm
  lines.push("swarm:");
  lines.push(`  rpm: ${rpm}`);
  lines.push(`  max_personas: ${maxPersonas}`);
  lines.push("");

  // output
  lines.push("output:");
  lines.push(`  dir: ${yamlStr(outputDir)}`);
  lines.push("");

  return lines.join("\n");
}

const FIELD =
  "w-full px-3 py-2 text-sm bg-background border border-border rounded-lg outline-none focus:border-ring focus:ring-2 focus:ring-ring/25 transition-colors";
const LABEL = "text-xs text-muted-foreground";

export default function Flows() {
  const [flows, setFlows] = useState<FlowDraft[]>([newFlow()]);
  const [icp, setIcp] = useState<IcpValue>("auto");
  const [rpm, setRpm] = useState<number>(5);
  const [maxPersonas, setMaxPersonas] = useState<number>(6);
  const outputDir = ".sim";
  const [copied, setCopied] = useState(false);

  const yaml = useMemo(
    () => buildYaml(flows, icp, rpm, maxPersonas, outputDir),
    [flows, icp, rpm, maxPersonas]
  );

  async function copy() {
    try {
      await navigator.clipboard.writeText(yaml);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      setCopied(false);
    }
  }

  return (
    <div className="mx-auto w-full max-w-5xl px-6 py-8">
      <header className="mb-6">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">
          Flows
        </h1>
        <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
          Author your{" "}
          <code className="font-mono text-foreground">sim.yml</code>. This is a
          client-side helper — there is no backend save yet, so copy the
          generated file into your repo root. The{" "}
          <code className="font-mono text-foreground">simulationlabs/gate</code>{" "}
          GitHub Action reads it and runs these flows{" "}
          <span className="text-foreground">from CI, not from this dashboard</span>{" "}
          (see <code className="font-mono text-foreground">docs/ci.md</code>).
        </p>
      </header>

      <div className="grid gap-8 lg:grid-cols-[1fr_minmax(0,26rem)]">
        {/* editor column */}
        <div className="flex flex-col gap-8">
          <section>
            <h2 className="mb-1 text-sm font-medium text-foreground">Flows</h2>
            <p className="mb-3 text-xs text-muted-foreground">
              Each flow is one behavioral test: a real goal on a real page and a
              bar it must clear.
            </p>
            <FlowEditor flows={flows} onChange={setFlows} />
          </section>

          <section>
            <h2 className="mb-1 text-sm font-medium text-foreground">
              ICP — behavioral segments
            </h2>
            <p className="mb-3 text-xs text-muted-foreground">
              Which personas the swarm sends at every flow.
            </p>
            <IcpPicker value={icp} onChange={setIcp} />
          </section>

          <section>
            <h2 className="mb-3 text-sm font-medium text-foreground">Swarm</h2>
            <div className="grid gap-4 sm:grid-cols-2">
              <label className="flex flex-col gap-2">
                <span className={LABEL}>
                  rpm — shared Holo rate limit (free tier ~5)
                </span>
                <input
                  className={FIELD}
                  type="number"
                  min={1}
                  step={1}
                  value={rpm}
                  onChange={(e) => {
                    const n = parseInt(e.target.value, 10);
                    setRpm(Number.isNaN(n) ? 1 : Math.max(1, n));
                  }}
                />
              </label>
              <label className="flex flex-col gap-2">
                <span className={LABEL}>max_personas — cap per run</span>
                <input
                  className={FIELD}
                  type="number"
                  min={1}
                  max={ALL_IDS.length}
                  step={1}
                  value={maxPersonas}
                  onChange={(e) => {
                    const n = parseInt(e.target.value, 10);
                    setMaxPersonas(Number.isNaN(n) ? 1 : Math.max(1, n));
                  }}
                />
              </label>
            </div>
          </section>
        </div>

        {/* live YAML column */}
        <div className="flex flex-col gap-3 lg:sticky lg:top-6 lg:self-start">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-medium text-foreground">
              <code className="font-mono">sim.yml</code>
            </h2>
            <button
              type="button"
              onClick={copy}
              className="px-3 py-1.5 rounded-lg bg-primary text-primary-foreground text-xs font-medium hover:opacity-90 transition-opacity"
            >
              {copied ? "Copied" : "Copy"}
            </button>
          </div>
          <pre className="overflow-x-auto rounded-xl border border-border bg-hover p-4 font-mono text-xs leading-relaxed text-foreground">
            <code>{yaml}</code>
          </pre>
          <p className="text-xs text-muted-foreground">
            Commit this as <code className="font-mono">sim.yml</code> at your
            repo root, then add the{" "}
            <code className="font-mono">simulationlabs/gate</code> step to your
            workflow.
          </p>
        </div>
      </div>
    </div>
  );
}
